[2022-12-17T04:16:18.055+0000] {processor.py:153} INFO - Started process (PID=33) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:16:18.057+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:16:18.058+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:16:18.058+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:16:18.096+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:16:18.094+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:16:18.097+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:16:18.116+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.065 seconds
[2022-12-17T04:16:48.591+0000] {processor.py:153} INFO - Started process (PID=108) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:16:48.593+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:16:48.594+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:16:48.594+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:16:48.603+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:16:48.602+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:16:48.604+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:16:48.641+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.054 seconds
[2022-12-17T04:17:18.985+0000] {processor.py:153} INFO - Started process (PID=171) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:17:18.986+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:17:18.987+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:17:18.987+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:17:18.997+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:17:18.996+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:17:18.998+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:17:19.015+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.033 seconds
[2022-12-17T04:17:49.612+0000] {processor.py:153} INFO - Started process (PID=245) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:17:49.613+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:17:49.616+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:17:49.616+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:17:49.630+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:17:49.627+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:17:49.631+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:17:49.654+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.048 seconds
[2022-12-17T04:18:19.898+0000] {processor.py:153} INFO - Started process (PID=319) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:18:19.901+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:18:19.903+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:18:19.903+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:18:19.918+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:18:19.916+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:18:19.918+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:18:19.940+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.049 seconds
[2022-12-17T04:18:50.202+0000] {processor.py:153} INFO - Started process (PID=391) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:18:50.204+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:18:50.205+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:18:50.205+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:18:50.215+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:18:50.214+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:18:50.216+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:18:50.233+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.035 seconds
[2022-12-17T04:19:20.861+0000] {processor.py:153} INFO - Started process (PID=457) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:19:20.864+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:19:20.865+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:19:20.865+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:19:20.879+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:19:20.877+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:19:20.880+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:19:20.902+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.046 seconds
[2022-12-17T04:19:51.074+0000] {processor.py:153} INFO - Started process (PID=532) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:19:51.075+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:19:51.076+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:19:51.076+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:19:51.084+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:19:51.083+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:19:51.085+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:19:51.102+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.032 seconds
[2022-12-17T04:20:21.484+0000] {processor.py:153} INFO - Started process (PID=608) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:20:21.485+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:20:21.486+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:20:21.486+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:20:21.496+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:20:21.494+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:20:21.497+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:20:21.515+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.034 seconds
[2022-12-17T04:20:51.772+0000] {processor.py:153} INFO - Started process (PID=672) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:20:51.773+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:20:51.774+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:20:51.774+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:20:51.783+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:20:51.781+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:20:51.784+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:20:51.802+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.034 seconds
[2022-12-17T04:21:22.247+0000] {processor.py:153} INFO - Started process (PID=747) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:21:22.250+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:21:22.251+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:21:22.251+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:21:22.262+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:21:22.260+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:21:22.262+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:21:22.283+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.041 seconds
[2022-12-17T04:22:25.780+0000] {processor.py:153} INFO - Started process (PID=33) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:22:25.782+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:22:25.784+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:22:25.784+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:22:25.808+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:22:25.806+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:22:25.809+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:22:25.827+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.049 seconds
[2022-12-17T04:22:56.021+0000] {processor.py:153} INFO - Started process (PID=71) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:22:56.023+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:22:56.024+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:22:56.024+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:22:56.037+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:22:56.036+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:22:56.039+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:22:56.058+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.042 seconds
[2022-12-17T04:23:26.361+0000] {processor.py:153} INFO - Started process (PID=95) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:23:26.363+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:23:26.365+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:23:26.365+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:23:26.378+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:23:26.375+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:23:26.379+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:23:26.400+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.042 seconds
[2022-12-17T04:23:56.653+0000] {processor.py:153} INFO - Started process (PID=132) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:23:56.655+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:23:56.656+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:23:56.656+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:23:56.676+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:23:56.674+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:23:56.677+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:23:56.698+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.051 seconds
[2022-12-17T04:24:26.921+0000] {processor.py:153} INFO - Started process (PID=168) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:24:26.923+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:24:26.924+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:24:26.924+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:24:26.936+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:24:26.934+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:24:26.937+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:24:26.957+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.039 seconds
[2022-12-17T04:24:57.185+0000] {processor.py:153} INFO - Started process (PID=192) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:24:57.187+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:24:57.189+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:24:57.189+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:24:57.203+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:24:57.201+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:24:57.205+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:24:57.228+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.048 seconds
[2022-12-17T04:25:27.456+0000] {processor.py:153} INFO - Started process (PID=228) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:25:27.458+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:25:27.460+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:25:27.460+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:25:27.476+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:25:27.474+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:25:27.478+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:25:27.499+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.049 seconds
[2022-12-17T04:25:57.699+0000] {processor.py:153} INFO - Started process (PID=265) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:25:57.703+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:25:57.705+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:25:57.705+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:25:57.721+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:25:57.719+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:25:57.722+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:25:57.742+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.049 seconds
[2022-12-17T04:26:28.027+0000] {processor.py:153} INFO - Started process (PID=291) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:26:28.029+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:26:28.032+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:26:28.032+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:26:28.046+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:26:28.044+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:26:28.047+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:26:28.066+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.044 seconds
[2022-12-17T04:26:58.288+0000] {processor.py:153} INFO - Started process (PID=328) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:26:58.289+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:26:58.290+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:26:58.290+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:26:58.297+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:26:58.296+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:26:58.298+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:26:58.314+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.029 seconds
[2022-12-17T04:27:28.513+0000] {processor.py:153} INFO - Started process (PID=366) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:27:28.515+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:27:28.516+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:27:28.516+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:27:28.525+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:27:28.524+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:27:28.526+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:27:28.542+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.032 seconds
[2022-12-17T04:27:58.755+0000] {processor.py:153} INFO - Started process (PID=391) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:27:58.756+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:27:58.758+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:27:58.758+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:27:58.767+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:27:58.766+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:27:58.768+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:27:58.784+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.033 seconds
[2022-12-17T04:29:13.791+0000] {processor.py:153} INFO - Started process (PID=33) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:29:13.793+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:29:13.794+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:29:13.794+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:29:13.809+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:29:13.807+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:29:13.811+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:29:13.836+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.049 seconds
[2022-12-17T04:29:44.043+0000] {processor.py:153} INFO - Started process (PID=70) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:29:44.045+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:29:44.047+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:29:44.047+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:29:44.060+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:29:44.058+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:29:44.060+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:29:44.080+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.043 seconds
[2022-12-17T04:30:14.314+0000] {processor.py:153} INFO - Started process (PID=94) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:30:14.316+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:30:14.317+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:30:14.316+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:30:14.326+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:30:14.324+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:30:14.328+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:30:14.348+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.036 seconds
[2022-12-17T04:30:44.580+0000] {processor.py:153} INFO - Started process (PID=132) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:30:44.582+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:30:44.584+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:30:44.584+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:30:44.601+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:30:44.600+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:30:44.602+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:30:44.624+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.049 seconds
[2022-12-17T04:31:14.800+0000] {processor.py:153} INFO - Started process (PID=168) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:31:14.802+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:31:14.804+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:31:14.804+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:31:14.818+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:31:14.816+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:31:14.819+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:31:14.840+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.044 seconds
[2022-12-17T04:31:45.100+0000] {processor.py:153} INFO - Started process (PID=193) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:31:45.103+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:31:45.104+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:31:45.104+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:31:45.118+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:31:45.116+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:31:45.119+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:31:45.142+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.048 seconds
[2022-12-17T04:32:15.359+0000] {processor.py:153} INFO - Started process (PID=229) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:32:15.361+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:32:15.363+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:32:15.363+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:32:15.375+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:32:15.373+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:32:15.376+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:32:15.397+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.043 seconds
[2022-12-17T04:32:45.628+0000] {processor.py:153} INFO - Started process (PID=265) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:32:45.630+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:32:45.632+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:32:45.632+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:32:45.645+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:32:45.643+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:32:45.646+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:32:45.669+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.046 seconds
[2022-12-17T04:33:15.889+0000] {processor.py:153} INFO - Started process (PID=291) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:33:15.891+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:33:15.892+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:33:15.892+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:33:15.903+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:33:15.901+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:33:15.903+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:33:15.922+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.036 seconds
[2022-12-17T04:33:46.117+0000] {processor.py:153} INFO - Started process (PID=328) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:33:46.119+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:33:46.120+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:33:46.119+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:33:46.128+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:33:46.127+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:33:46.129+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:33:46.146+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.032 seconds
[2022-12-17T04:34:16.397+0000] {processor.py:153} INFO - Started process (PID=365) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:34:16.398+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:34:16.399+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:34:16.398+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:34:16.407+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:34:16.405+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:34:16.407+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:34:16.424+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.029 seconds
[2022-12-17T04:34:46.644+0000] {processor.py:153} INFO - Started process (PID=390) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:34:46.645+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:34:46.646+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:34:46.646+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:34:46.655+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:34:46.653+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:34:46.656+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:34:46.675+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.034 seconds
[2022-12-17T04:35:16.918+0000] {processor.py:153} INFO - Started process (PID=427) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:35:16.920+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:35:16.921+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:35:16.921+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:35:16.929+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:35:16.927+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:35:16.929+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:35:16.947+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.030 seconds
[2022-12-17T04:35:47.124+0000] {processor.py:153} INFO - Started process (PID=463) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:35:47.125+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:35:47.126+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:35:47.126+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:35:47.133+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:35:47.132+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:35:47.133+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:35:47.148+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.026 seconds
[2022-12-17T04:36:17.345+0000] {processor.py:153} INFO - Started process (PID=497) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:36:17.346+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:36:17.347+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:36:17.347+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:36:17.354+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:36:17.353+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:36:17.355+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:36:17.370+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.027 seconds
[2022-12-17T04:36:47.602+0000] {processor.py:153} INFO - Started process (PID=525) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:36:47.604+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:36:47.605+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:36:47.605+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:36:47.621+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:36:47.619+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:36:47.622+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:36:47.647+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.051 seconds
[2022-12-17T04:37:17.857+0000] {processor.py:153} INFO - Started process (PID=563) to work on /opt/airflow/dags/scheduler.py
[2022-12-17T04:37:17.859+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17T04:37:17.861+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:37:17.860+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17T04:37:17.872+0000] {logging_mixin.py:137} INFO - [2022-12-17T04:37:17.871+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 7, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
[2022-12-17T04:37:17.873+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17T04:37:17.896+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/scheduler.py took 0.042 seconds
[2022-12-17 04:45:04,062] {processor.py:163} INFO - Started process (PID=135) to work on /opt/airflow/dags/scheduler.py
[2022-12-17 04:45:04,074] {processor.py:642} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17 04:45:04,076] {logging_mixin.py:109} INFO - [2022-12-17 04:45:04,076] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17 04:45:05,657] {logging_mixin.py:109} INFO - [2022-12-17 04:45:05,644] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 236, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'warehouse' (-2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 17, in <module>
    connection = mysql.connector.connect(user=user, password=password, host=host, port=port, database=database, auth_plugin='mysql_native_password')
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/__init__.py", line 272, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 85, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/abstracts.py", line 1014, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 242, in _open_connection
    sqlstate=exc.sqlstate)
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'warehouse' (-2)
[2022-12-17 04:45:05,715] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17 04:45:05,755] {processor.py:171} INFO - Processing /opt/airflow/dags/scheduler.py took 1.722 seconds
[2022-12-17 04:45:35,949] {processor.py:163} INFO - Started process (PID=169) to work on /opt/airflow/dags/scheduler.py
[2022-12-17 04:45:35,962] {processor.py:642} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17 04:45:35,972] {logging_mixin.py:109} INFO - [2022-12-17 04:45:35,972] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17 04:45:36,472] {logging_mixin.py:109} INFO - [2022-12-17 04:45:36,451] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 236, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'warehouse' (-2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 17, in <module>
    connection = mysql.connector.connect(user=user, password=password, host=host, port=port, database=database, auth_plugin='mysql_native_password')
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/__init__.py", line 272, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 85, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/abstracts.py", line 1014, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 242, in _open_connection
    sqlstate=exc.sqlstate)
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'warehouse' (-2)
[2022-12-17 04:45:36,610] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17 04:45:36,725] {processor.py:171} INFO - Processing /opt/airflow/dags/scheduler.py took 0.804 seconds
[2022-12-17 04:46:07,048] {processor.py:163} INFO - Started process (PID=187) to work on /opt/airflow/dags/scheduler.py
[2022-12-17 04:46:07,053] {processor.py:642} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17 04:46:07,056] {logging_mixin.py:109} INFO - [2022-12-17 04:46:07,056] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17 04:46:07,233] {logging_mixin.py:109} INFO - [2022-12-17 04:46:07,226] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 236, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'warehouse' (-2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 17, in <module>
    connection = mysql.connector.connect(user=user, password=password, host=host, port=port, database=database, auth_plugin='mysql_native_password')
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/__init__.py", line 272, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 85, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/abstracts.py", line 1014, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 242, in _open_connection
    sqlstate=exc.sqlstate)
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'warehouse' (-2)
[2022-12-17 04:46:07,261] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17 04:46:07,280] {processor.py:171} INFO - Processing /opt/airflow/dags/scheduler.py took 0.243 seconds
[2022-12-17 04:46:37,323] {processor.py:163} INFO - Started process (PID=221) to work on /opt/airflow/dags/scheduler.py
[2022-12-17 04:46:37,327] {processor.py:642} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17 04:46:37,329] {logging_mixin.py:109} INFO - [2022-12-17 04:46:37,329] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17 04:46:37,558] {logging_mixin.py:109} INFO - [2022-12-17 04:46:37,549] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 236, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'warehouse' (-2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 17, in <module>
    connection = mysql.connector.connect(user=user, password=password, host=host, port=port, database=database, auth_plugin='mysql_native_password')
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/__init__.py", line 272, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 85, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/abstracts.py", line 1014, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 242, in _open_connection
    sqlstate=exc.sqlstate)
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'warehouse' (-2)
[2022-12-17 04:46:37,585] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17 04:46:37,606] {processor.py:171} INFO - Processing /opt/airflow/dags/scheduler.py took 0.289 seconds
[2022-12-17 04:47:07,785] {processor.py:163} INFO - Started process (PID=239) to work on /opt/airflow/dags/scheduler.py
[2022-12-17 04:47:07,788] {processor.py:642} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17 04:47:07,791] {logging_mixin.py:109} INFO - [2022-12-17 04:47:07,790] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17 04:47:07,957] {logging_mixin.py:109} INFO - [2022-12-17 04:47:07,950] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 236, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'warehouse' (-2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 17, in <module>
    connection = mysql.connector.connect(user=user, password=password, host=host, port=port, database=database, auth_plugin='mysql_native_password')
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/__init__.py", line 272, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 85, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/abstracts.py", line 1014, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 242, in _open_connection
    sqlstate=exc.sqlstate)
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'warehouse' (-2)
[2022-12-17 04:47:07,984] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17 04:47:08,005] {processor.py:171} INFO - Processing /opt/airflow/dags/scheduler.py took 0.225 seconds
[2022-12-17 04:47:38,059] {processor.py:163} INFO - Started process (PID=273) to work on /opt/airflow/dags/scheduler.py
[2022-12-17 04:47:38,062] {processor.py:642} INFO - Processing file /opt/airflow/dags/scheduler.py for tasks to queue
[2022-12-17 04:47:38,064] {logging_mixin.py:109} INFO - [2022-12-17 04:47:38,063] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler.py
[2022-12-17 04:47:38,262] {logging_mixin.py:109} INFO - [2022-12-17 04:47:38,251] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/scheduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 236, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'warehouse' (-2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler.py", line 17, in <module>
    connection = mysql.connector.connect(user=user, password=password, host=host, port=port, database=database, auth_plugin='mysql_native_password')
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/__init__.py", line 272, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 85, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/abstracts.py", line 1014, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 242, in _open_connection
    sqlstate=exc.sqlstate)
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'warehouse' (-2)
[2022-12-17 04:47:38,293] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler.py
[2022-12-17 04:47:38,318] {processor.py:171} INFO - Processing /opt/airflow/dags/scheduler.py took 0.265 seconds
